package TransporteApp;


/**
* TransporteApp/TransportePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from transporte.idl
* martes 14 de junio de 2022 09:07:03 PM COT
*/

public abstract class TransportePOA extends org.omg.PortableServer.Servant
 implements TransporteApp.TransporteOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("setDestino", new java.lang.Integer (0));
    _methods.put ("buscarDestinoInArray", new java.lang.Integer (1));
    _methods.put ("verDisponibilidad", new java.lang.Integer (2));
    _methods.put ("getPrecio", new java.lang.Integer (3));
    _methods.put ("hacerReservacion", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // TransporteApp/Transporte/setDestino
       {
         String nombre = in.read_string ();
         double precio = in.read_double ();
         int disponible = in.read_long ();
         this.setDestino (nombre, precio, disponible);
         out = $rh.createReply();
         break;
       }

       case 1:  // TransporteApp/Transporte/buscarDestinoInArray
       {
         String destino = in.read_string ();
         int $result = (int)0;
         $result = this.buscarDestinoInArray (destino);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // TransporteApp/Transporte/verDisponibilidad
       {
         String destino = in.read_string ();
         String $result = null;
         $result = this.verDisponibilidad (destino);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // TransporteApp/Transporte/getPrecio
       {
         String destino = in.read_string ();
         double $result = (double)0;
         $result = this.getPrecio (destino);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 4:  // TransporteApp/Transporte/hacerReservacion
       {
         String destino = in.read_string ();
         String $result = null;
         $result = this.hacerReservacion (destino);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:TransporteApp/Transporte:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Transporte _this() 
  {
    return TransporteHelper.narrow(
    super._this_object());
  }

  public Transporte _this(org.omg.CORBA.ORB orb) 
  {
    return TransporteHelper.narrow(
    super._this_object(orb));
  }


} // class TransportePOA
