package TransporteApp;


/**
* TransporteApp/Transporte.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from transporte.idl
* martes 14 de junio de 2022 09:07:03 PM COT
*/

public interface Transporte extends TransporteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Transporte
