package TransporteApp;

/**
* TransporteApp/TransporteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from transporte.idl
* martes 14 de junio de 2022 09:07:03 PM COT
*/

public final class TransporteHolder implements org.omg.CORBA.portable.Streamable
{
  public TransporteApp.Transporte value = null;

  public TransporteHolder ()
  {
  }

  public TransporteHolder (TransporteApp.Transporte initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TransporteApp.TransporteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TransporteApp.TransporteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TransporteApp.TransporteHelper.type ();
  }

}
